# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDPnDYORNq0EykzZLncZncwlJ0Hpd-7T
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
st.title("Advertising Effectiveness Sean Santos")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X axis",["Tv", "Radio", "Newspaper"])
y_var=st.sidebar.selectbox("y Axis", ["sales"])

#scatter
fig=px.scatter(df,x=x_var,y=y_var)
st.plotly_chart(fig)

#df
st.write("###THis is the data")
st.dataframe(df)

#map
st.title("Im the map")
fig=px.scatter_mapbox(df, lat='latitude', lon='longitude', size='newspaper', hover_name='City',
                      color='sales', color_continuous_scale=px.colors.sequential.Viridis)
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)
